name = "lists"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./out"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "RATELIMIT"
id = "0f53da9b1408408d868bb42df55d4570"
